name: Build project
on: [push, pull_request]
jobs:
  install-test-lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test
      - name: Run Linter
        run: |
          npm run lint