name: Create debug APK
on:
  push:
    tags:
      - '*'
  branches:
    - main
build-android:
    needs: install-test-lint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Debug
        run: |
          cd android && ./gradlew assembleDebug
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/release/
